name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: write
    pages: write
    id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          ref: main

      - name: update version in repo
        env:
          tag: ${{ github.ref_name }}
        run: |
          tmp=$(mktemp)
          jq --arg version $tag '.versions |= [$version] + .' versions.json > "$tmp" && mv "$tmp" versions.json
          sed -i "/define VERSION/c\#define VERSION \"$tag\"" lnpos/100_config.ino
          git config --global user.name 'Alan Bits'
          git config --global user.email 'alan@lnbits.com'
          git commit -am "[CHORE] update version to $tag"
          git push
          git push --delete origin $tag
          git tag -fa $tag -m "update via workflow"
          git push --tags

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: build, release and upload on github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          sh install.sh
          devices=$(jq '.devices[]' versions.json -r)
          uploads=""
          for device in $devices; do
              sh build.sh $device
              mv build/lnpos.ino.bin ./lnpos-$device.ino.bin
              uploads="$uploads ./lnpos-$device.ino.bin"
              mv build/lnpos.ino.partitions.bin ./lnpos-$device.ino.partitions.bin
              uploads="$uploads ./lnpos-$device.ino.partitions.bin"
              mv build/lnpos.ino.bootloader.bin ./lnpos-$device.ino.bootloader.bin
              uploads="$uploads ./lnpos-$device.ino.bootloader.bin"
          done
          gh release create "$tag" --generate-notes $uploads
